### ISSUE TITLE
Develop User Profile Creation Endpoint

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#12]
Description:
Create an endpoint that allows users to dynamically create and save their profiles, including name, skill tags, profile picture, and bio, to the database.

Tasks:

Create an Express route for POST /api/users/profile to handle profile creation.
Implement validation to ensure mandatory fields like name, skills, and bio are correctly provided.
Handle optional fields like the profile picture URL (default placeholder if missing).
Write logic to store user-provided data into MongoDB.
Return success/error responses for successful or invalid submissions.

Estimated Time: 48 hours

Please claim this issue

**Comment by CoderSharma97** [comment]
claim

**Comment by SinghArsh04** [comment]
claim

**Comment by shubh5921** [comment]
claim
