### ISSUE TITLE
Implement Profile Update Logic

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#13]
Description:
Develop the backend functionality that allows users to edit and update their profile details, such as skill tags, bio, and profile picture.

Tasks:

Set up an Express route for PUT /api/users/profile/:id for profile updates.
Implement database logic to selectively update only provided fields (skills, bio, profile picture).
Validate data integrity (e.g., skill tags must be valid strings, bio must adhere to a character limit).
Handle error scenarios such as invalid user IDs or database failures.
Write unit tests to ensure the update functionality behaves as expected under different conditions.

Estimated Time: 60 hours

Please claim this issue

**Comment by CoderSharma97** [comment]
claim

**Comment by prath47** [comment]
can i contribute ?
assign this to me

**Comment by ANJALIJAISWAL4213** [comment]
please write /claim only  for claiming

**Comment by Vardaan-02** [comment]
hey i am assigned to this but the bot says that i am not assigned please help

**Comment by Vardaan-02** [comment]
should i make the pull request again ?

**Comment by VatsalBhuva11** [comment]
@Vardaan-02 you are assigned, no issues

**Comment by Vardaan-02** [comment]
similar issue faced here https://github.com/opencodeiiita/SponsoHive-Backend/issues/11

**Comment by VatsalBhuva11** [comment]
> similar issue faced here [opencodeiiita/SponsoHive-Backend#11](https://github.com/opencodeiiita/SponsoHive-Backend/issues/11)

fixed

**Comment by ANJALIJAISWAL4213** [comment]
@prath47 do continue working on this issue
