### ISSUE TITLE
Develop the Portfolio Section for User Profiles

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#14]
Description:
Create functionality to allow users to add, view, and edit portfolio links showcasing their work.

Tasks:

Create database schema/model for storing portfolio links under a user’s profile.
Set up the Express route POST /api/users/profile/:id/portfolio for adding portfolio items.
Implement logic for GET /api/users/profile/:id/portfolio to fetch a user's portfolio data.
Validate user access to ensure only the respective user can add or edit their portfolio.
Write unit tests to verify database CRUD operations for the portfolio section.

Estimated Time: 60 hours

Please claim this issue

**Comment by ANJALIJAISWAL4213** [comment]
please write /claim to claim

**Comment by ayush-patel1** [comment]
claim
@ANJALIJAISWAL4213
