### ISSUE TITLE
Set up the Session Scheduling Calendar Endpoint

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#17]
Description:
Create an endpoint that allows users to view, book, and schedule time slots for sessions using an integrated calendar system.

Tasks:

Set up a backend endpoint POST /api/sessions/schedule for booking sessions.
Allow users to specify details like date, time, session type, and duration.
Validate requested time slots to ensure they are available and not conflicting with other user schedules.
Create logic to save session data in MongoDB with fields like userId, startTime, endTime, and sessionType.
Return appropriate success or error responses based on validation.

Estimated Time: 48 hours

Please claim this issue.

**Comment by HGRgamer** [comment]
claim
