### ISSUE TITLE
Create Notifications for Upcoming Sessions

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#18]
Description:
Implement a system to send notifications to users for their upcoming scheduled sessions.

Tasks:

Set up backend logic to trigger notifications (via email, push notifications, or real-time alerts with Socket.IO).
Use session data to determine upcoming sessions within a specified time frame (e.g., 24 hours ahead).
Create a function that scans the database to find upcoming sessions and sends notifications to users.
Integrate Socket.IO or email services like SendGrid for real-time or scheduled notifications.
Write unit tests to ensure notifications are sent accurately and in the correct timeframe.

Estimated Time: 60 hours

**Comment by shubh5921** [comment]
claim

**Comment by PrinkalDhingra** [comment]
@AyMk544 kindly register first and then claim

**Comment by AyMk544** [comment]
i registered just after claiming, pls accept my pr

**Comment by PrinkalDhingra** [comment]
@AyMk544 create a new pr

**Comment by AyMk544** [comment]
@PrinkalDhingra I created a new pr, but I'm not assigned to this issue currently, please reassign me and check the pr.

**Comment by PrinkalDhingra** [comment]
@AyMk544 this issue is now assigned to someone else as you didn't register before . Please wait for the next issue.

**Comment by PrinkalDhingra** [comment]
@shubh5921 update on the issue as it is past the deadline.

**Comment by ayush-patel1** [comment]
claim

**Comment by Darkknight0125** [comment]
No one assigned.
Now claim?
/Claim

**Comment by ayush-patel1** [comment]
claim please assign me

**Comment by ayush-patel1** [comment]
@PrinkalDhingra thanks
