### ISSUE TITLE
Develop Session Availability Logic

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#19]
Description:
Implement logic to handle the availability of time slots on the calendar and prevent double bookings.

Tasks:

Query the database to check for overlapping sessions during a proposed booking time slot.
Develop a utility function to determine free slots in a user’s calendar.
Create the endpoint GET /api/sessions/availability to return available times for session requests.
Implement validation to reject conflicting session requests.
Test the availability logic using sample data to ensure no double bookings occur.

Estimated Time: 60 hours

**Comment by PrinkalDhingra** [comment]
@ScorchedPearl please provide an update on the issue.
