### ISSUE TITLE
Develop the login controller

### ISSUE THREAD

**Issue by vanshdvn2505** [opencodeiiita/SkillSync-Backend#5]
Implement a Sign-in API to enable users to authenticate and access our platform's services securely. This API will serve as the gateway for users to log in using their credentials and obtain the necessary authorization to interact with our system.

Key Requirements:

User Authentication: The API should authenticate users by validating their credentials, such as email and password.
Secure Authentication: Some function are already provided in user models for better and easier implementation, like comparePassword, generateToken etc.
Error Handling: Ensure clear and descriptive error messages for different scenarios (e.g., incorrect credentials, expired session).
Session Management: Implement a mechanism for managing user sessions securely, including session expiration and token generation.
All response needed to be sent in the following JSON format
```json
{
    "result": false,
    "error": "${For debugging}",
    "message": "${Message to be displayed to user as a toast}"
}
```
Any question you can reach us on discord.

Once completed, submit a pull request with the code, and include relevant documentation for integration.
Time: 48 hours.

Please comment to claim the issue.

**Comment by 07CalC** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
assigned 07CalC

**Comment by 07CalC** [comment]
no package.json provided

**Comment by ANJALIJAISWAL4213** [comment]
> no package.json provided
just folder structure is given initially do
npm init -y

**Comment by PrinkalDhingra** [comment]
@07CalC update?

**Comment by 07CalC** [comment]
sorry for the delay, i was traveling
