### ISSUE TITLE
Controller for review

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SkillSync-Backend#54]
Hello contributors 

In this task you are required to create :

1)MODEL : with fields like userID , description , date
2) CONTROLLER : write a controller for to write and save the review. Also a function to sort the review based on date.
3)ROUTE: add the corresponding route in the routes file. 
4) IMPORTANT: only users who were part of a particular session are allowed to give reviews corresponding to that session.

NOTE : 1)Create a new file in model and controllers folder for the review and add the route in the route file. 

Time: 48 hrs

Comment to claim

**Comment by HGRgamer** [comment]
claim

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Darkknight0125** [comment]
/claim
No one assigned now.

**Comment by HGRgamer** [comment]
/claim
@PrinkalDhingra please assign it to me as I was the first one to claim

**Comment by ayush-patel1** [comment]
claim
