### ISSUE TITLE
Enroll and Uneroll for sessions

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SkillSync-Backend#57]
Hello Contributors

In this task you are required to create a controller to add and remove users from sessions.

TASKS:
1)In the user schema add a field in the form of array which stores the session IDs of all the sessions the user is enrolled in.
2)In the session schema add a field  in the form of array  which stores the user ID of all the users who have enrolled for the particular session.
3)Similarly write functions to remove participants who do not wish to join a session.
4)Write all the functions in the controller file of sessions.
5)Add the necessary routes in the route file.

Time - 48 hrs

comment to claim

**Comment by rajbir40** [comment]
claim
