### ISSUE TITLE
Implement the note-taking feature

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SkillSync-Backend#59]
Hello contributors

In this task you have to implement the note-taking feature provided by skillsync.

TASKS:
Create a schema in the models file for notes which consists of field like:
1)userID
2)sessionID
3)description
4)date and time

Time-24 hrs

NOTE: Comment to claim.

**Comment by Darkknight0125** [comment]
Claim

**Comment by rajbir40** [comment]
Claim

**Comment by ayush-patel1** [comment]
claim
