### ISSUE TITLE
Implement Session Scheduling Logic

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#8]
Develop the backend endpoints and logic for users to book, schedule, and manage skill-sharing sessions.

Tasks:

Design endpoints to handle session creation, rescheduling, and cancellation.
Integrate an intuitive date and time-check mechanism to avoid session conflicts.
Write logic to send notifications/reminders (via Socket.IO) for upcoming sessions.
Create database models to store session data with session IDs, dates, user IDs, and status.
Write unit tests to validate the session scheduling system under different scenarios.

Estimated Time: 96 hours

Note: Please claim this issue

**Comment by Vardaan-02** [comment]
claim

**Comment by shubh5921** [comment]
claim
