### ISSUE TITLE
Write Unit Tests for Key Backend Routes & Logic

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SkillSync-Backend#9]
Description:
Write comprehensive unit tests to validate the functionality of key backend routes (authentication, user profile creation, session scheduling, and notifications).

Tasks:

Write unit tests for authentication logic (signup, login, error handling).
Validate CRUD operations on the user profile endpoints.
Write tests for session scheduling logic to ensure proper date/time handling.
Write tests to ensure Socket.IO notifications fire under correct conditions.
Use Jest or a similar testing library to maintain test integrity and CI/CD compatibility.

Estimated Time: 96 hours

**Comment by kalim-Asim** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
no need to claim it's open for all

**Comment by PrinkalDhingra** [comment]
Issue completed
